name: RTx-Attribute
module_name: RTx::Attribute
version: 0.00_01
abstract: RT Attribute Extension
author: Autrijus Tang (autrijus@autrijus.org)
distribution_type: module
build_requires:
  Test::More: 0
private:
  directory:
    - inc
generated_by: Module::Install version 0.23
